import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";



export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} antialiased bg-zinc-950 text-zinc-50  max-w-screen-2xl mx-auto px-4`}
      >
        {children}
      </body>
    </html>
  );
}
